/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ups.edu.ec.vista;

import javax.swing.JMenu;
import javax.swing.JMenuItem;
import ups.edu.ec.controlador.ControladorTelefono;

import ups.edu.ec.controlador.ControladorUsuario;

/**
 *
 * @author user
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private VentanaRegistrarUsuario ventanaRegistrarUsuario;

    private VentanaIniciarSesion ventanaIniciarSesion;
    private ControladorUsuario controladorUsuario;
    private ControladorTelefono controladorTelefono;
    private VentanaBuscarUsuarios ventanaBuscarUsuarios;
    private VentanaGestionTelefono ventanaGestionTelefono;
    /**
     * Creates new form NewMDIApplication
     */
    public VentanaPrincipal() {
        initComponents();
        menuTelefono.setVisible(false);
        menuItemCerrarSesion.setVisible(false);
        controladorUsuario = new ControladorUsuario();

        ventanaRegistrarUsuario = new VentanaRegistrarUsuario(controladorUsuario);
        ventanaBuscarUsuarios = new VentanaBuscarUsuarios(controladorUsuario, controladorTelefono);
       
    }

    public JMenuItem getInicarMenuItem() {
        return InicarMenuItem;
    }

    public JMenuItem getRegistarMenuItem() {
        return menuRegistar;
    }

    public JMenuItem getMenuItemCerrarSesion() {
        return menuItemCerrarSesion;
    }

    public JMenu getMenuTelefono() {
        return menuTelefono;
    }

    public JMenu getMenuIniciarS() {
        return menuIniciarS;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuIniciarS = new javax.swing.JMenu();
        InicarMenuItem = new javax.swing.JMenuItem();
        menuRegistar = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        menuItemCerrarSesion = new javax.swing.JMenuItem();
        menuItemListarTelefonoPorUsuario = new javax.swing.JMenuItem();
        menuTelefono = new javax.swing.JMenu();
        menuItemGestionTelefono = new javax.swing.JMenuItem();
        menuItemGestionUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        desktopPane.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AGENDA TELEFONICA");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(100, 110, 300, 170);

        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        menuIniciarS.setMnemonic('f');
        menuIniciarS.setText("Inicio");

        InicarMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        InicarMenuItem.setMnemonic('o');
        InicarMenuItem.setText("Iniciar Sesion");
        InicarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicarMenuItemActionPerformed(evt);
            }
        });
        menuIniciarS.add(InicarMenuItem);

        menuRegistar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuRegistar.setMnemonic('s');
        menuRegistar.setText("Registar");
        menuRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistarActionPerformed(evt);
            }
        });
        menuIniciarS.add(menuRegistar);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        menuIniciarS.add(exitMenuItem);

        menuItemCerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuItemCerrarSesion.setText("Cerra Sesion");
        menuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarSesionActionPerformed(evt);
            }
        });
        menuIniciarS.add(menuItemCerrarSesion);

        menuItemListarTelefonoPorUsuario.setText("Listar telefonos");
        menuItemListarTelefonoPorUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarTelefonoPorUsuarioActionPerformed(evt);
            }
        });
        menuIniciarS.add(menuItemListarTelefonoPorUsuario);

        menuBar.add(menuIniciarS);

        menuTelefono.setMnemonic('e');
        menuTelefono.setText("Gestinar");

        menuItemGestionTelefono.setMnemonic('t');
        menuItemGestionTelefono.setText("Telefono");
        menuItemGestionTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGestionTelefonoActionPerformed(evt);
            }
        });
        menuTelefono.add(menuItemGestionTelefono);

        menuItemGestionUsuario.setMnemonic('y');
        menuItemGestionUsuario.setText("Usuario");
        menuItemGestionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGestionUsuarioActionPerformed(evt);
            }
        });
        menuTelefono.add(menuItemGestionUsuario);

        menuBar.add(menuTelefono);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void InicarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicarMenuItemActionPerformed
        ventanaIniciarSesion = new VentanaIniciarSesion(controladorUsuario, this);
        desktopPane.add(ventanaIniciarSesion);

        ventanaIniciarSesion.setVisible(true);
    }//GEN-LAST:event_InicarMenuItemActionPerformed

    private void menuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarSesionActionPerformed

        menuTelefono.setVisible(false);
        menuItemCerrarSesion.setVisible(false);
        menuIniciarS.setVisible(true);
        menuRegistar.setVisible(true);

    }//GEN-LAST:event_menuItemCerrarSesionActionPerformed

    private void menuRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistarActionPerformed
        if (!ventanaRegistrarUsuario.isVisible()) {
            desktopPane.add(ventanaRegistrarUsuario);
            ventanaRegistrarUsuario.setVisible(true);

        }
    }//GEN-LAST:event_menuRegistarActionPerformed

    private void menuItemGestionTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGestionTelefonoActionPerformed
        ventanaGestionTelefono= new VentanaGestionTelefono(controladorUsuario, controladorTelefono);
        desktopPane.add(ventanaGestionTelefono);

        ventanaGestionTelefono.setVisible(true);

    }//GEN-LAST:event_menuItemGestionTelefonoActionPerformed

    private void menuItemListarTelefonoPorUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarTelefonoPorUsuarioActionPerformed


    }//GEN-LAST:event_menuItemListarTelefonoPorUsuarioActionPerformed

    private void menuItemGestionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGestionUsuarioActionPerformed
        ventanaBuscarUsuarios = new VentanaBuscarUsuarios(controladorUsuario, controladorTelefono);
        desktopPane.add(ventanaBuscarUsuarios);

        ventanaBuscarUsuarios.setVisible(true);
    }//GEN-LAST:event_menuItemGestionUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem InicarMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuIniciarS;
    private javax.swing.JMenuItem menuItemCerrarSesion;
    private javax.swing.JMenuItem menuItemGestionTelefono;
    private javax.swing.JMenuItem menuItemGestionUsuario;
    private javax.swing.JMenuItem menuItemListarTelefonoPorUsuario;
    private javax.swing.JMenuItem menuRegistar;
    private javax.swing.JMenu menuTelefono;
    // End of variables declaration//GEN-END:variables

}
